// frontend/src/app/features/onboarding/onboarding.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatNativeDateModule } from '@angular/material/core';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatStepperModule } from '@angular/material/stepper';
import { ProfileService } from '../../core/services/profile.service';
import { COMMA, ENTER } from '@angular/cdk/keycodes';
import { MatChipInputEvent } from '@angular/material/chips';

@Component({
  selector: 'app-onboarding',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
    MatIconModule,
    MatChipsModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatProgressSpinnerModule,
    MatStepperModule,
  ],
  template: `
    <div class="onboarding-page">
      <div class="onboarding-container">
        <div class="logo">BirthTech.ai</div>
        <h1>Let's Get to Know You</h1>
        <p class="subtitle">
          Tell us about your pregnancy so we can personalize your care experience.
        </p>

        @if (error()) {
          <div class="error-message">{{ error() }}</div>
        }

        <mat-card class="form-card">
          <form [formGroup]="form" (ngSubmit)="onSubmit()">
            <mat-stepper linear #stepper>
              <!-- Step 1: Pregnancy Info -->
              <mat-step [stepControl]="form">
                <ng-template matStepLabel>Pregnancy Info</ng-template>
                <div class="step-content">
                  <mat-form-field class="form-field" appearance="outline">
                    <mat-label>Current Pregnancy Month</mat-label>
                    <mat-select formControlName="pregnancyMonth">
                      @for (month of months; track month.value) {
                        <mat-option [value]="month.value">
                          {{ month.label }}
                        </mat-option>
                      }
                    </mat-select>
                    <mat-hint>Select your current month of pregnancy</mat-hint>
                  </mat-form-field>

                  <mat-form-field class="form-field" appearance="outline">
                    <mat-label>Expected Due Date</mat-label>
                    <input matInput [matDatepicker]="picker" formControlName="dueDate" />
                    <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
                    <mat-datepicker #picker></mat-datepicker>
                  </mat-form-field>

                  <div class="step-actions">
                    <button mat-raised-button color="primary" matStepperNext type="button">
                      Next
                    </button>
                  </div>
                </div>
              </mat-step>

              <!-- Step 2: Physical Info -->
              <mat-step>
                <ng-template matStepLabel>Your Details</ng-template>
                <div class="step-content">
                  <div class="row">
                    <mat-form-field class="form-field half" appearance="outline">
                      <mat-label>Height (cm)</mat-label>
                      <input matInput type="number" formControlName="heightCm" />
                    </mat-form-field>

                    <mat-form-field class="form-field half" appearance="outline">
                      <mat-label>Weight (kg)</mat-label>
                      <input matInput type="number" formControlName="weightKg" />
                    </mat-form-field>
                  </div>

                  <mat-form-field class="form-field" appearance="outline">
                    <mat-label>Diet Preference</mat-label>
                    <mat-select formControlName="dietPreference">
                      <mat-option value="non-veg">Non-Vegetarian</mat-option>
                      <mat-option value="veg">Vegetarian</mat-option>
                      <mat-option value="vegan">Vegan</mat-option>
                    </mat-select>
                  </mat-form-field>

                  <div class="step-actions">
                    <button mat-button matStepperPrevious type="button">Back</button>
                    <button mat-raised-button color="primary" matStepperNext type="button">
                      Next
                    </button>
                  </div>
                </div>
              </mat-step>

              <!-- Step 3: Allergies -->
              <mat-step>
                <ng-template matStepLabel>Allergies</ng-template>
                <div class="step-content">
                  <p class="info-text">
                    Add any food allergies so we can customize your meal recommendations.
                    Press Enter after each allergy.
                  </p>

                  <mat-form-field class="form-field" appearance="outline">
                    <mat-label>Food Allergies (optional)</mat-label>
                    <mat-chip-grid #chipGrid>
                      @for (allergy of allergies(); track allergy) {
                        <mat-chip-row (removed)="removeAllergy(allergy)">
                          {{ allergy }}
                          <button matChipRemove>
                            <mat-icon>cancel</mat-icon>
                          </button>
                        </mat-chip-row>
                      }
                    </mat-chip-grid>
                    <input
                      placeholder="Type and press Enter..."
                      [matChipInputFor]="chipGrid"
                      [matChipInputSeparatorKeyCodes]="separatorKeysCodes"
                      (matChipInputTokenEnd)="addAllergy($event)"
                    />
                  </mat-form-field>

                  <div class="step-actions">
                    <button mat-button matStepperPrevious type="button">Back</button>
                    <button
                      mat-raised-button
                      color="primary"
                      type="submit"
                      [disabled]="loading() || form.invalid"
                    >
                      @if (loading()) {
                        <mat-spinner diameter="20"></mat-spinner>
                      } @else {
                        Start My Journey
                      }
                    </button>
                  </div>
                </div>
              </mat-step>
            </mat-stepper>
          </form>
        </mat-card>
      </div>
    </div>
  `,
  styles: [`
    .onboarding-page {
      min-height: 100vh;
      background: linear-gradient(135deg, #FDF2F8 0%, #EDE9FE 100%);
      padding: 24px;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .onboarding-container {
      max-width: 600px;
      width: 100%;
    }

    .logo {
      text-align: center;
      font-size: 1.5rem;
      font-weight: 700;
      color: #8B5CF6;
      margin-bottom: 24px;
    }

    h1 {
      text-align: center;
      font-size: 2rem;
      color: #1F2937;
      margin-bottom: 8px;
    }

    .subtitle {
      text-align: center;
      color: #6B7280;
      margin-bottom: 32px;
    }

    .form-card {
      padding: 32px;
      border-radius: 16px;
    }

    .step-content {
      padding: 24px 0;
    }

    .form-field {
      width: 100%;
      margin-bottom: 16px;
    }

    .row {
      display: flex;
      gap: 16px;
    }

    .half {
      flex: 1;
    }

    .info-text {
      color: #6B7280;
      margin-bottom: 16px;
      line-height: 1.5;
    }

    .step-actions {
      display: flex;
      justify-content: flex-end;
      gap: 16px;
      margin-top: 24px;
    }

    .error-message {
      background: #FEE2E2;
      color: #DC2626;
      padding: 12px 16px;
      border-radius: 8px;
      margin-bottom: 16px;
      text-align: center;
    }

    ::ng-deep .mat-horizontal-stepper-header-container {
      margin-bottom: 16px;
    }

    @media (max-width: 480px) {
      .row {
        flex-direction: column;
        gap: 0;
      }
    }
  `],
})
export class OnboardingComponent {
  form: FormGroup;
  loading = signal(false);
  error = signal('');
  allergies = signal<string[]>([]);
  separatorKeysCodes = [ENTER, COMMA];

  months = [
    { value: 1, label: 'Month 1 (Weeks 1-4)' },
    { value: 2, label: 'Month 2 (Weeks 5-8)' },
    { value: 3, label: 'Month 3 (Weeks 9-13)' },
    { value: 4, label: 'Month 4 (Weeks 14-17)' },
    { value: 5, label: 'Month 5 (Weeks 18-22)' },
    { value: 6, label: 'Month 6 (Weeks 23-27)' },
    { value: 7, label: 'Month 7 (Weeks 28-31)' },
    { value: 8, label: 'Month 8 (Weeks 32-35)' },
    { value: 9, label: 'Month 9 (Weeks 36-40)' },
  ];

  constructor(
    private fb: FormBuilder,
    private profileService: ProfileService,
    private router: Router
  ) {
    this.form = this.fb.group({
      pregnancyMonth: [null, Validators.required],
      dueDate: [null, Validators.required],
      heightCm: [null],
      weightKg: [null],
      dietPreference: ['non-veg', Validators.required],
    });
  }

  addAllergy(event: MatChipInputEvent): void {
    const value = (event.value || '').trim();
    if (value) {
      this.allergies.update((allergies) => [...allergies, value]);
    }
    event.chipInput!.clear();
  }

  removeAllergy(allergy: string): void {
    this.allergies.update((allergies) => allergies.filter((a) => a !== allergy));
  }

  onSubmit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.loading.set(true);
    this.error.set('');

    const formValue = this.form.value;
    const profile = {
      pregnancyMonth: formValue.pregnancyMonth,
      dueDate: formValue.dueDate.toISOString(),
      heightCm: formValue.heightCm,
      weightKg: formValue.weightKg,
      dietPreference: formValue.dietPreference,
      allergies: this.allergies(),
    };

    this.profileService.createProfile(profile).subscribe({
      next: () => {
        this.loading.set(false);
        this.router.navigate(['/dashboard']);
      },
      error: (err) => {
        this.loading.set(false);
        this.error.set(err.error?.message || 'Failed to create profile. Please try again.');
      },
    });
  }
}

// app/onboarding/page.tsx
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Heart, Loader2, ChevronRight, ChevronLeft, X } from 'lucide-react';

export default function OnboardingPage() {
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [allergyInput, setAllergyInput] = useState('');

  const [formData, setFormData] = useState({
    pregnancyMonth: 0,
    dueDate: '',
    heightCm: '',
    weightKg: '',
    dietPreference: 'non-veg',
    allergies: [] as string[],
  });

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (!token) {
      router.push('/auth/login');
    }
  }, [router]);

  const months = [
    { value: 1, label: 'Month 1', weeks: 'Weeks 1-4' },
    { value: 2, label: 'Month 2', weeks: 'Weeks 5-8' },
    { value: 3, label: 'Month 3', weeks: 'Weeks 9-13' },
    { value: 4, label: 'Month 4', weeks: 'Weeks 14-17' },
    { value: 5, label: 'Month 5', weeks: 'Weeks 18-22' },
    { value: 6, label: 'Month 6', weeks: 'Weeks 23-27' },
    { value: 7, label: 'Month 7', weeks: 'Weeks 28-31' },
    { value: 8, label: 'Month 8', weeks: 'Weeks 32-35' },
    { value: 9, label: 'Month 9', weeks: 'Weeks 36-40' },
  ];

  const addAllergy = () => {
    if (allergyInput.trim() && !formData.allergies.includes(allergyInput.trim())) {
      setFormData({
        ...formData,
        allergies: [...formData.allergies, allergyInput.trim()],
      });
      setAllergyInput('');
    }
  };

  const removeAllergy = (allergy: string) => {
    setFormData({
      ...formData,
      allergies: formData.allergies.filter((a) => a !== allergy),
    });
  };

  const handleSubmit = async () => {
    setLoading(true);
    setError('');

    try {
      const token = localStorage.getItem('token');
      const res = await fetch('/api/profile', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          ...formData,
          heightCm: formData.heightCm ? parseFloat(formData.heightCm) : null,
          weightKg: formData.weightKg ? parseFloat(formData.weightKg) : null,
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || 'Failed to save profile');
      }

      router.push('/dashboard');
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen py-12 px-4">
      <div className="max-w-xl mx-auto">
        <div className="text-center mb-8">
          <Link href="/" className="inline-flex items-center gap-2 mb-6">
            <Heart className="w-8 h-8 text-pink-500" fill="#ec4899" />
            <span className="text-xl font-bold bg-gradient-to-r from-purple-600 to-pink-500 bg-clip-text text-transparent">
              BirthTech.ai
            </span>
          </Link>
          <h1 className="text-2xl font-bold text-gray-900">Let's Get to Know You</h1>
          <p className="text-gray-600 mt-2">
            Tell us about your pregnancy so we can personalize your care
          </p>
        </div>

        {/* Progress Steps */}
        <div className="flex items-center justify-center gap-2 mb-8">
          {[1, 2, 3].map((s) => (
            <div
              key={s}
              className={`w-3 h-3 rounded-full ${
                s === step ? 'bg-purple-500' : s < step ? 'bg-purple-300' : 'bg-gray-200'
              }`}
            />
          ))}
        </div>

        <div className="card">
          {error && (
            <div className="bg-red-50 text-red-600 p-4 rounded-xl mb-6 text-sm">
              {error}
            </div>
          )}

          {/* Step 1: Pregnancy Info */}
          {step === 1 && (
            <div className="space-y-6">
              <h2 className="text-lg font-semibold text-gray-900">Pregnancy Information</h2>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-3">
                  Current Pregnancy Month
                </label>
                <div className="grid grid-cols-3 gap-2">
                  {months.map((month) => (
                    <button
                      key={month.value}
                      type="button"
                      onClick={() => setFormData({ ...formData, pregnancyMonth: month.value })}
                      className={`p-3 rounded-xl text-center transition-all ${
                        formData.pregnancyMonth === month.value
                          ? 'bg-purple-500 text-white'
                          : 'bg-gray-50 text-gray-700 hover:bg-gray-100'
                      }`}
                    >
                      <div className="font-medium">{month.label}</div>
                      <div className="text-xs opacity-75">{month.weeks}</div>
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Expected Due Date
                </label>
                <input
                  type="date"
                  className="input-field"
                  value={formData.dueDate}
                  onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
                />
              </div>

              <button
                onClick={() => setStep(2)}
                disabled={!formData.pregnancyMonth || !formData.dueDate}
                className="btn-primary w-full flex items-center justify-center gap-2"
              >
                Continue
                <ChevronRight className="w-5 h-5" />
              </button>
            </div>
          )}

          {/* Step 2: Physical Info */}
          {step === 2 && (
            <div className="space-y-6">
              <h2 className="text-lg font-semibold text-gray-900">Your Details</h2>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Height (cm)
                  </label>
                  <input
                    type="number"
                    className="input-field"
                    placeholder="165"
                    value={formData.heightCm}
                    onChange={(e) => setFormData({ ...formData, heightCm: e.target.value })}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Weight (kg)
                  </label>
                  <input
                    type="number"
                    className="input-field"
                    placeholder="60"
                    value={formData.weightKg}
                    onChange={(e) => setFormData({ ...formData, weightKg: e.target.value })}
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-3">
                  Diet Preference
                </label>
                <div className="grid grid-cols-3 gap-2">
                  {[
                    { value: 'non-veg', label: 'Non-Veg' },
                    { value: 'veg', label: 'Vegetarian' },
                    { value: 'vegan', label: 'Vegan' },
                  ].map((diet) => (
                    <button
                      key={diet.value}
                      type="button"
                      onClick={() => setFormData({ ...formData, dietPreference: diet.value })}
                      className={`p-3 rounded-xl text-center transition-all ${
                        formData.dietPreference === diet.value
                          ? 'bg-purple-500 text-white'
                          : 'bg-gray-50 text-gray-700 hover:bg-gray-100'
                      }`}
                    >
                      {diet.label}
                    </button>
                  ))}
                </div>
              </div>

              <div className="flex gap-3">
                <button
                  onClick={() => setStep(1)}
                  className="btn-secondary flex-1 flex items-center justify-center gap-2"
                >
                  <ChevronLeft className="w-5 h-5" />
                  Back
                </button>
                <button
                  onClick={() => setStep(3)}
                  className="btn-primary flex-1 flex items-center justify-center gap-2"
                >
                  Continue
                  <ChevronRight className="w-5 h-5" />
                </button>
              </div>
            </div>
          )}

          {/* Step 3: Allergies */}
          {step === 3 && (
            <div className="space-y-6">
              <h2 className="text-lg font-semibold text-gray-900">Food Allergies (Optional)</h2>
              <p className="text-sm text-gray-600">
                Add any food allergies so we can customize your meal recommendations
              </p>

              <div>
                <div className="flex gap-2">
                  <input
                    type="text"
                    className="input-field flex-1"
                    placeholder="e.g., Peanuts, Shellfish"
                    value={allergyInput}
                    onChange={(e) => setAllergyInput(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), addAllergy())}
                  />
                  <button
                    type="button"
                    onClick={addAllergy}
                    className="px-4 py-2 bg-gray-100 text-gray-700 rounded-xl hover:bg-gray-200"
                  >
                    Add
                  </button>
                </div>

                {formData.allergies.length > 0 && (
                  <div className="flex flex-wrap gap-2 mt-4">
                    {formData.allergies.map((allergy) => (
                      <span
                        key={allergy}
                        className="inline-flex items-center gap-1 bg-purple-100 text-purple-700 px-3 py-1 rounded-full text-sm"
                      >
                        {allergy}
                        <button onClick={() => removeAllergy(allergy)}>
                          <X className="w-4 h-4" />
                        </button>
                      </span>
                    ))}
                  </div>
                )}
              </div>

              <div className="flex gap-3">
                <button
                  onClick={() => setStep(2)}
                  className="btn-secondary flex-1 flex items-center justify-center gap-2"
                >
                  <ChevronLeft className="w-5 h-5" />
                  Back
                </button>
                <button
                  onClick={handleSubmit}
                  disabled={loading}
                  className="btn-primary flex-1 flex items-center justify-center gap-2"
                >
                  {loading ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      Saving...
                    </>
                  ) : (
                    'Start My Journey'
                  )}
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
