// frontend/src/app/features/profile/profile.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatNativeDateModule } from '@angular/material/core';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatToolbarModule } from '@angular/material/toolbar';
import { ProfileService, PregnancyProfile } from '../../core/services/profile.service';
import { COMMA, ENTER } from '@angular/cdk/keycodes';
import { MatChipInputEvent } from '@angular/material/chips';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [
    CommonModule,
    RouterLink,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
    MatIconModule,
    MatChipsModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatProgressSpinnerModule,
    MatToolbarModule,
  ],
  template: `
    <div class="profile-page">
      <mat-toolbar class="header" color="primary">
        <button mat-icon-button routerLink="/dashboard">
          <mat-icon>arrow_back</mat-icon>
        </button>
        <span>Edit Profile</span>
      </mat-toolbar>

      <div class="profile-container">
        @if (loading()) {
          <div class="loading-state">
            <mat-spinner diameter="48"></mat-spinner>
          </div>
        } @else {
          @if (error()) {
            <div class="error-message">{{ error() }}</div>
          }

          @if (success()) {
            <div class="success-message">
              <mat-icon>check_circle</mat-icon>
              Profile updated successfully!
            </div>
          }

          <mat-card class="form-card">
            <form [formGroup]="form" (ngSubmit)="onSubmit()">
              <mat-form-field class="form-field" appearance="outline">
                <mat-label>Current Pregnancy Month</mat-label>
                <mat-select formControlName="pregnancyMonth">
                  @for (month of months; track month.value) {
                    <mat-option [value]="month.value">
                      {{ month.label }}
                    </mat-option>
                  }
                </mat-select>
              </mat-form-field>

              <mat-form-field class="form-field" appearance="outline">
                <mat-label>Expected Due Date</mat-label>
                <input matInput [matDatepicker]="picker" formControlName="dueDate" />
                <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
                <mat-datepicker #picker></mat-datepicker>
              </mat-form-field>

              <div class="row">
                <mat-form-field class="form-field half" appearance="outline">
                  <mat-label>Height (cm)</mat-label>
                  <input matInput type="number" formControlName="heightCm" />
                </mat-form-field>

                <mat-form-field class="form-field half" appearance="outline">
                  <mat-label>Weight (kg)</mat-label>
                  <input matInput type="number" formControlName="weightKg" />
                </mat-form-field>
              </div>

              <mat-form-field class="form-field" appearance="outline">
                <mat-label>Diet Preference</mat-label>
                <mat-select formControlName="dietPreference">
                  <mat-option value="non-veg">Non-Vegetarian</mat-option>
                  <mat-option value="veg">Vegetarian</mat-option>
                  <mat-option value="vegan">Vegan</mat-option>
                </mat-select>
              </mat-form-field>

              <mat-form-field class="form-field" appearance="outline">
                <mat-label>Food Allergies</mat-label>
                <mat-chip-grid #chipGrid>
                  @for (allergy of allergies(); track allergy) {
                    <mat-chip-row (removed)="removeAllergy(allergy)">
                      {{ allergy }}
                      <button matChipRemove>
                        <mat-icon>cancel</mat-icon>
                      </button>
                    </mat-chip-row>
                  }
                </mat-chip-grid>
                <input
                  placeholder="Type and press Enter..."
                  [matChipInputFor]="chipGrid"
                  [matChipInputSeparatorKeyCodes]="separatorKeysCodes"
                  (matChipInputTokenEnd)="addAllergy($event)"
                />
              </mat-form-field>

              <div class="form-actions">
                <button mat-button type="button" routerLink="/dashboard">
                  Cancel
                </button>
                <button
                  mat-raised-button
                  color="primary"
                  type="submit"
                  [disabled]="saving()"
                >
                  @if (saving()) {
                    <mat-spinner diameter="20"></mat-spinner>
                  } @else {
                    Save Changes
                  }
                </button>
              </div>
            </form>
          </mat-card>
        }
      </div>
    </div>
  `,
  styles: [`
    .profile-page {
      min-height: 100vh;
      background: #FDF2F8;
    }

    .header {
      background: linear-gradient(135deg, #8B5CF6 0%, #F472B6 100%);
    }

    .profile-container {
      max-width: 600px;
      margin: 0 auto;
      padding: 24px;
    }

    .loading-state {
      display: flex;
      justify-content: center;
      padding: 48px;
    }

    .form-card {
      padding: 32px;
      border-radius: 16px;
    }

    .form-field {
      width: 100%;
      margin-bottom: 16px;
    }

    .row {
      display: flex;
      gap: 16px;
    }

    .half {
      flex: 1;
    }

    .form-actions {
      display: flex;
      justify-content: flex-end;
      gap: 16px;
      margin-top: 24px;
    }

    .error-message {
      background: #FEE2E2;
      color: #DC2626;
      padding: 12px 16px;
      border-radius: 8px;
      margin-bottom: 16px;
    }

    .success-message {
      background: #D1FAE5;
      color: #065F46;
      padding: 12px 16px;
      border-radius: 8px;
      margin-bottom: 16px;
      display: flex;
      align-items: center;
      gap: 8px;
    }

    @media (max-width: 480px) {
      .row {
        flex-direction: column;
        gap: 0;
      }
    }
  `],
})
export class ProfileComponent implements OnInit {
  form: FormGroup;
  loading = signal(true);
  saving = signal(false);
  error = signal('');
  success = signal(false);
  allergies = signal<string[]>([]);
  separatorKeysCodes = [ENTER, COMMA];

  months = [
    { value: 1, label: 'Month 1 (Weeks 1-4)' },
    { value: 2, label: 'Month 2 (Weeks 5-8)' },
    { value: 3, label: 'Month 3 (Weeks 9-13)' },
    { value: 4, label: 'Month 4 (Weeks 14-17)' },
    { value: 5, label: 'Month 5 (Weeks 18-22)' },
    { value: 6, label: 'Month 6 (Weeks 23-27)' },
    { value: 7, label: 'Month 7 (Weeks 28-31)' },
    { value: 8, label: 'Month 8 (Weeks 32-35)' },
    { value: 9, label: 'Month 9 (Weeks 36-40)' },
  ];

  constructor(
    private fb: FormBuilder,
    private profileService: ProfileService,
    private router: Router
  ) {
    this.form = this.fb.group({
      pregnancyMonth: [null, Validators.required],
      dueDate: [null, Validators.required],
      heightCm: [null],
      weightKg: [null],
      dietPreference: ['non-veg', Validators.required],
    });
  }

  ngOnInit(): void {
    this.loadProfile();
  }

  loadProfile(): void {
    this.profileService.getProfile().subscribe({
      next: (profile) => {
        if (profile) {
          this.form.patchValue({
            pregnancyMonth: profile.pregnancyMonth,
            dueDate: new Date(profile.dueDate),
            heightCm: profile.heightCm,
            weightKg: profile.weightKg,
            dietPreference: profile.dietPreference,
          });
          this.allergies.set(profile.allergies || []);
        }
        this.loading.set(false);
      },
      error: () => {
        this.loading.set(false);
        this.router.navigate(['/onboarding']);
      },
    });
  }

  addAllergy(event: MatChipInputEvent): void {
    const value = (event.value || '').trim();
    if (value) {
      this.allergies.update((allergies) => [...allergies, value]);
    }
    event.chipInput!.clear();
  }

  removeAllergy(allergy: string): void {
    this.allergies.update((allergies) => allergies.filter((a) => a !== allergy));
  }

  onSubmit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.saving.set(true);
    this.error.set('');
    this.success.set(false);

    const formValue = this.form.value;
    const profile = {
      pregnancyMonth: formValue.pregnancyMonth,
      dueDate: formValue.dueDate.toISOString(),
      heightCm: formValue.heightCm,
      weightKg: formValue.weightKg,
      dietPreference: formValue.dietPreference,
      allergies: this.allergies(),
    };

    this.profileService.updateProfile(profile).subscribe({
      next: () => {
        this.saving.set(false);
        this.success.set(true);
        setTimeout(() => this.success.set(false), 3000);
      },
      error: (err) => {
        this.saving.set(false);
        this.error.set(err.error?.message || 'Failed to update profile. Please try again.');
      },
    });
  }
}

// app/profile/page.tsx
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Heart, ArrowLeft, Loader2, X, CheckCircle } from 'lucide-react';

export default function ProfilePage() {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  const [allergyInput, setAllergyInput] = useState('');

  const [formData, setFormData] = useState({
    pregnancyMonth: 0,
    dueDate: '',
    heightCm: '',
    weightKg: '',
    dietPreference: 'non-veg',
    allergies: [] as string[],
  });

  const months = [
    { value: 1, label: 'Month 1', weeks: 'Weeks 1-4' },
    { value: 2, label: 'Month 2', weeks: 'Weeks 5-8' },
    { value: 3, label: 'Month 3', weeks: 'Weeks 9-13' },
    { value: 4, label: 'Month 4', weeks: 'Weeks 14-17' },
    { value: 5, label: 'Month 5', weeks: 'Weeks 18-22' },
    { value: 6, label: 'Month 6', weeks: 'Weeks 23-27' },
    { value: 7, label: 'Month 7', weeks: 'Weeks 28-31' },
    { value: 8, label: 'Month 8', weeks: 'Weeks 32-35' },
    { value: 9, label: 'Month 9', weeks: 'Weeks 36-40' },
  ];

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (!token) {
      router.push('/auth/login');
      return;
    }

    // Fetch profile
    fetch('/api/profile', {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then((res) => res.json())
      .then((data) => {
        if (data.error) {
          router.push('/onboarding');
          return;
        }
        setFormData({
          pregnancyMonth: data.pregnancyMonth,
          dueDate: data.dueDate?.split('T')[0] || '',
          heightCm: data.heightCm?.toString() || '',
          weightKg: data.weightKg?.toString() || '',
          dietPreference: data.dietPreference || 'non-veg',
          allergies: data.allergies || [],
        });
        setLoading(false);
      })
      .catch(() => {
        router.push('/onboarding');
      });
  }, [router]);

  const addAllergy = () => {
    if (allergyInput.trim() && !formData.allergies.includes(allergyInput.trim())) {
      setFormData({
        ...formData,
        allergies: [...formData.allergies, allergyInput.trim()],
      });
      setAllergyInput('');
    }
  };

  const removeAllergy = (allergy: string) => {
    setFormData({
      ...formData,
      allergies: formData.allergies.filter((a) => a !== allergy),
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setError('');
    setSuccess(false);

    try {
      const token = localStorage.getItem('token');
      const res = await fetch('/api/profile', {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          ...formData,
          heightCm: formData.heightCm ? parseFloat(formData.heightCm) : null,
          weightKg: formData.weightKg ? parseFloat(formData.weightKg) : null,
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || 'Failed to update profile');
      }

      setSuccess(true);
      setTimeout(() => setSuccess(false), 3000);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-purple-500" />
      </div>
    );
  }

  return (
    <div className="min-h-screen py-8 px-4">
      <div className="max-w-xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <Link
            href="/dashboard"
            className="p-2 hover:bg-white rounded-full transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Edit Profile</h1>
            <p className="text-gray-600">Update your pregnancy information</p>
          </div>
        </div>

        {error && (
          <div className="bg-red-50 text-red-600 p-4 rounded-xl mb-6 text-sm">
            {error}
          </div>
        )}

        {success && (
          <div className="bg-green-50 text-green-600 p-4 rounded-xl mb-6 text-sm flex items-center gap-2">
            <CheckCircle className="w-5 h-5" />
            Profile updated successfully!
          </div>
        )}

        <form onSubmit={handleSubmit} className="card space-y-6">
          {/* Pregnancy Month */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-3">
              Current Pregnancy Month
            </label>
            <div className="grid grid-cols-3 gap-2">
              {months.map((month) => (
                <button
                  key={month.value}
                  type="button"
                  onClick={() => setFormData({ ...formData, pregnancyMonth: month.value })}
                  className={`p-3 rounded-xl text-center transition-all ${
                    formData.pregnancyMonth === month.value
                      ? 'bg-purple-500 text-white'
                      : 'bg-gray-50 text-gray-700 hover:bg-gray-100'
                  }`}
                >
                  <div className="font-medium">{month.label}</div>
                  <div className="text-xs opacity-75">{month.weeks}</div>
                </button>
              ))}
            </div>
          </div>

          {/* Due Date */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Expected Due Date
            </label>
            <input
              type="date"
              className="input-field"
              value={formData.dueDate}
              onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
            />
          </div>

          {/* Height & Weight */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Height (cm)
              </label>
              <input
                type="number"
                className="input-field"
                placeholder="165"
                value={formData.heightCm}
                onChange={(e) => setFormData({ ...formData, heightCm: e.target.value })}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Weight (kg)
              </label>
              <input
                type="number"
                className="input-field"
                placeholder="60"
                value={formData.weightKg}
                onChange={(e) => setFormData({ ...formData, weightKg: e.target.value })}
              />
            </div>
          </div>

          {/* Diet Preference */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-3">
              Diet Preference
            </label>
            <div className="grid grid-cols-3 gap-2">
              {[
                { value: 'non-veg', label: 'Non-Veg' },
                { value: 'veg', label: 'Vegetarian' },
                { value: 'vegan', label: 'Vegan' },
              ].map((diet) => (
                <button
                  key={diet.value}
                  type="button"
                  onClick={() => setFormData({ ...formData, dietPreference: diet.value })}
                  className={`p-3 rounded-xl text-center transition-all ${
                    formData.dietPreference === diet.value
                      ? 'bg-purple-500 text-white'
                      : 'bg-gray-50 text-gray-700 hover:bg-gray-100'
                  }`}
                >
                  {diet.label}
                </button>
              ))}
            </div>
          </div>

          {/* Allergies */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Food Allergies
            </label>
            <div className="flex gap-2">
              <input
                type="text"
                className="input-field flex-1"
                placeholder="e.g., Peanuts, Shellfish"
                value={allergyInput}
                onChange={(e) => setAllergyInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), addAllergy())}
              />
              <button
                type="button"
                onClick={addAllergy}
                className="px-4 py-2 bg-gray-100 text-gray-700 rounded-xl hover:bg-gray-200"
              >
                Add
              </button>
            </div>

            {formData.allergies.length > 0 && (
              <div className="flex flex-wrap gap-2 mt-3">
                {formData.allergies.map((allergy) => (
                  <span
                    key={allergy}
                    className="inline-flex items-center gap-1 bg-purple-100 text-purple-700 px-3 py-1 rounded-full text-sm"
                  >
                    {allergy}
                    <button type="button" onClick={() => removeAllergy(allergy)}>
                      <X className="w-4 h-4" />
                    </button>
                  </span>
                ))}
              </div>
            )}
          </div>

          {/* Submit */}
          <div className="flex gap-3 pt-4">
            <Link
              href="/dashboard"
              className="btn-secondary flex-1 text-center"
            >
              Cancel
            </Link>
            <button
              type="submit"
              disabled={saving}
              className="btn-primary flex-1 flex items-center justify-center gap-2"
            >
              {saving ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Saving...
                </>
              ) : (
                'Save Changes'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
